# Generated by Django 4.2.2 on 2023-06-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('effect', models.CharField(max_length=200)),
                ('hearts', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('resale', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
