# Generated by Django 4.2.2 on 2023-06-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ingredient_duration_alter_ingredient_effect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200, null=True)),
                ('hearts', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=500, null=True)),
                ('resale', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500, null=True)),
                ('type_image', models.CharField(max_length=200, null=True)),
                ('ingredient1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i1', to='api.ingredient')),
                ('ingredient2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i2', to='api.ingredient')),
                ('ingredient3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i3', to='api.ingredient')),
                ('ingredient4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i4', to='api.ingredient')),
                ('ingredient5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i5', to='api.ingredient')),
            ],
        ),
    ]
